local uiModule = {}

function uiModule:Init()
    local Rayfield = loadstring(game:HttpGet('https://sirius.menu/rayfield'))()
    local plr = game:GetService("Players").LocalPlayer
    local teleportService = game:GetService("TeleportService")

    local Window = Rayfield:CreateWindow({
        Name = "Script Hub",
        LoadingTitle = "Loading Script Hub...",
        LoadingSubtitle = "by nyvexz",
        ConfigurationSaving = { Enabled = false }
    })

    -- 1. TAB: GAMES
    local GamesTab = Window:CreateTab("Games", 4483362458)
    GamesTab:CreateSection("Click to join (Script will auto-reload):")
    
    local function TeleportAndAutoRun(placeId)
        local numericId = tonumber(placeId)
        if not numericId then return end

        if writefile then
            local bootstrapperCode = [[
-- Automatically generated by Script Hub
repeat task.wait() until game:IsLoaded()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Damian-AFK404/scripthub/main/src/init.lua"))()
]]
            pcall(function()
                writefile("autoexec/scripthub_auto.lua", bootstrapperCode)
                writefile("scripthub_auto.lua", bootstrapperCode)
            end)
        end
        
        task.wait(0.3)

        -- Force Teleport handling
        pcall(function()
            teleportService:Teleport(numericId, plr)
        end)
    end

    GamesTab:CreateButton({
        Name = "Become a Brainrot",
        Callback = function() TeleportAndAutoRun(99255447043899) end,
    })
    
    GamesTab:CreateButton({
        Name = "Dropper RNG",
        Callback = function() TeleportAndAutoRun(110947318876182) end,
    })
    
    GamesTab:CreateButton({
        Name = "Paper Plane Simulator",
        Callback = function() TeleportAndAutoRun(110373292461174) end,
    })

    -- 2. TAB: SCRIPTS
    local ScriptsTab = Window:CreateTab("Scripts", 4483362458)

    -- 3. TAB: CREDITS
    local CreditsTab = Window:CreateTab("Credits", 4483362458)
    
    CreditsTab:CreateSection("Hub Information")
    CreditsTab:CreateLabel("hubName: Script Hub")
    CreditsTab:CreateLabel("version: 1.0.0")
    
    CreditsTab:CreateSection("Team")
    CreditsTab:CreateLabel("owner: nyvexz")
    CreditsTab:CreateLabel("developers: [nyvexz, Killuatrudi]")
    CreditsTab:CreateLabel("helpers: [nyvexz, Killuatrudi]")

    return Window, ScriptsTab
end

return uiModule
